version: '3'
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
